### ISSUE TITLE
Error when linking CXX executable exe_Map2Mesh_OFusionRGB1Label

### ISSUE THREAD

**Issue by YananJian** [ShunChengWu/SCFusion#2]
Hi! Thanks for the instructions! 

I'm using the docker image, installed torch and torchvision within the image, ran cmake **without** building **data generator** or **GUI**, I can see that step succeeded with all necessary files generated under ./build)
'make' failed though, at the very end at the linking step.

> [ 97%] Building CXX object App/Map2Mesh/CMakeFiles/exe_Map2Mesh_OFusionRGB1Label.dir/exe_Map2Mesh.cpp.o     </br>                                                    [ 98%] Linking CXX executable exe_Map2Mesh_OFusionRGB1Label                                                                                                     CMakeFiles/exe_Map2Mesh_OFusionRGB1Label.dir/exe_Map2Mesh.cpp.o: In function `main':                                                                            exe_Map2Mesh.cpp:(.text.startup+0x399): undefined reference to `tools::PathTool::create_folder(std::string)' 

Thanks in advance for any help on this!

**Comment by ShunChengWu** [comment]
hm... I cannot reproduce your error.
It seems like you have an issue w.r.t. the PathTool. It is a submodule of this project. Did you use this command to clone the code?
```
git clone --recurse-submodules https://github.com/ShunChengWu/SCFusion.git
```
Can you try 
```
git submodule init
git submodule update
```

**Comment by YananJian** [comment]
Thanks for the reply! I did exactly what you mentioned with git clone --recurse-submodules and submodule init, update.
I checked the submodule dirs, they are consistent with submodule master branches.

However, the linking error persists. I checked the location of PathTools. Does these locations look correct?

```
$PATH_TO_SCFusion/build/cxxtools/include/CxxTools/PathTool.hpp
$PATH_TO_SCFusion/build/cxxtools/build/src/cxxtools/include/PathTool.hpp
$PATH_TO_SCFusion/build/cxxtools/build/src/cxxtools/source/PathTool.cpp
```

**Comment by ShunChengWu** [comment]
all looks good for me. 
maybe the library linking is wrong?
Can you check if `CxxTools` is properly built and linked?

**Comment by YananJian** [comment]
I noticed $PATH_TO_SCFusion/build/cxxtools/build/src/cxxtools wasn't built so I ran cmake and make install there. 
This is the output

`[100%] Built target CxxTools                                                                                                                                                                                                                                                              Install the project...                                                                                                                                                                                                                                                                    -- Install configuration: ""                                                                                                                                                                                                                                                              -- Installing: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/lib/libCxxTools.a                                                                                                                                                                                                     -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/AwaitingThread.hpp                                                                                                                                                                                   -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/DataWorker.h                                                                                                                                                                                         -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/LogUtil.hpp                                                                                                                                                                                          -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/MemoryBlock.hpp                                                                                                                                                                                      -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/PathTool.hpp                                                                                                                                                                                         -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/Tools.hpp                                                                                                                                                                                            -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/log.h                                                                                                                                                                                                -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/parser.hpp                                                                                                                                                                                           -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/progressBar.hpp                                                                                                                                                                                      -- Up-to-date: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/include/CxxTools/thread_pool.hpp                                                                                                                                                                                      -- Installing: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/cmake/CxxToolsConfig.cmake                                                                                                                                                                                            -- Installing: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/cmake/CxxToolsConfigVersion.cmake                                                                                                                                                                                     -- Installing: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/cmake/CxxToolsTargets.cmake                                                                                                                                                                                           -- Installing: /work/SCFusion/build/cxxtools/build/src/cxxtools/bin/cmake/CxxToolsTargets-noconfig.cmake`

However the same error occurs when I run make under $PATH_TO_SCFusion/build/
`[ 97%] Linking CXX executable exe_Map2Mesh_OFusionRGB1Label                                                                                                                                                                                                                               CMakeFiles/exe_Map2Mesh_OFusionRGB1Label.dir/exe_Map2Mesh.cpp.o: In function `main':                                                                                                                                                                                                      exe_Map2Mesh.cpp:(.text.startup+0x399): undefined reference to `tools::PathTool::create_folder(std::string)'`

Looks like CxxTools was not linked correctly but I don't know how to fix it.

**Comment by ShunChengWu** [comment]
this is related to the library linking problem. In the worse case, you can change CMake to manually define the library path. 
Maybe you can print out
```
${cxxtools_DIR}
```
in
https://github.com/ShunChengWu/SCFusion/blob/ba263b511939a89d53f2da9603304fa71cfe7d65/cmake/UseCxxTools.cmake#L9
to check if the path is correctly defined. In your case, it should be 
`/work/SCFusion/build/cxxtools/build/src/cxxtools/bin`
