### ISSUE TITLE
Can you share a copy of the preprocessed dataset? (Or maybe just the GT files)

### ISSUE THREAD

**Issue by fereenwong** [ShunChengWu/SCFusion#3]

**Comment by ShunChengWu** [comment]
The generated data was not released because it is from ScanNet and it has terms of use. 
There is no guarantee but I may try to generate the data and one must agree the terms before downloading it.

**Comment by ShunChengWu** [comment]
The GT files will be uploaded soon

**Comment by ShunChengWu** [comment]
uploaded.
