### ISSUE TITLE
Error when make the Build

### ISSUE THREAD

**Issue by ark1234** [ShunChengWu/SCFusion#4]
Thank you so much for providing this awesome work and detail implementation instructions.

However, I make an error when compile it, I followed every of your instructions with your docker file.

I CMAKE with this"cmake -DBUILD_DATA_GENERATOR=True -DWITH_PYTORCH=True -DPYTORCH_PATH=/libtorch/ -DWITH_GUI=ON -DCMAKE_BUILD_TYPE=Release .."
I just run "make" and get error, I tried make different times, but didn't work. I am not familiar with this whole make stuff, could have a look for me. thanks a lot!
here is the error information:

[  2%] Built target PytorchCppTools
[  2%] Building CXX object libGUI3D/libGUI/CMakeFiles/imgui.dir/__/__/external/ImGUIFileDialog/ImGuiFileDialog/ImGuiFileDialog.cpp.o
In file included from /SCFusion/build/external/ImGUIFileDialog/ImGuiFileDialog/ImGuiFileDialog.cpp:44:0:
/SCFusion/build/external/ImGUI/imgui_internal.h:101:2: error: #error Please '#define IMGUI_DEFINE_MATH_OPERATORS' _BEFORE_ including imgui.h!

 #error Please '#define IMGUI_DEFINE_MATH_OPERATORS' _BEFORE_ including imgui.h!
  ^~~~~
/SCFusion/build/external/ImGUIFileDialog/ImGuiFileDialog/ImGuiFileDialog.cpp: In member function 'bool ImGuiFileDialog::FileDialog(const string&, ImGuiWindowFlags)':
/SCFusion/build/external/ImGUIFileDialog/ImGuiFileDialog/ImGuiFileDialog.cpp:682:47: error: no match for 'operator-' (operand types are 'ImVec2' and 'ImVec')
    ImVec2 size = ImGui::GetContentRegionMax() - ImVec2((float)dlg_optionsPaneWidth, itemsHeight);
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libGUI3D/libGUI/CMakeFiles/imgui.dir/build.make:94: recipe for target 'libGUI3D/libGUI/CMakeFiles/imgui.dir/__/__/external/ImGUIFileDialog/ImGuiFileDialog/ImGuiFileDialog.cpp.o' failed
make[2]: *** [libGUI3D/libGUI/CMakeFiles/imgui.dir/__/__/external/ImGUIFileDialog/ImGuiFileDialog/ImGuiFileDialog.cpp.o] Error 1
CMakeFiles/Makefile2:924: recipe for target 'libGUI3D/libGUI/CMakeFiles/imgui.dir/all' failed
make[1]: *** [libGUI3D/libGUI/CMakeFiles/imgui.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by ShunChengWu** [comment]
I have pushed a new version. If you compile from the source code it should work
